version: '3.8'

services:
  web:
    build: ./web
    ports:
      - "8080:443"
    volumes:
      - ./web:/var/www/html
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: tpsecu
      MONGO_INITDB_ROOT_USERNAME: tpuser
      MONGO_INITDB_ROOT_PASSWORD: tppass
    volumes:
      - ./db/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js 